sonata-project/SonataCacheBundle

Adapter/ApcCache.php

this PR let the bundle extension check apc extension only for PHP version superior to 5.5.0

fix opcache reset for php version > 5.5

---

Adapter/SymfonyCache.php
Tests/Adapter/SymfonyCacheTest.php
composer.json

I am targetting this branch, because this is a bug fix.
```markdown
- IP detection in SymfonyCache
```
There was a mistake in the detection of the IP version based on the count of ".".

Fixed ip detection and removed unused use statement

---

Adapter/SymfonyCache.php
DependencyInjection/Configuration.php
DependencyInjection/SonataCacheExtension.php
Resources/config/cache.xml
Resources/doc/reference/installation.rst
Tests/Adapter/SymfonyCacheTest.php
Tests/DependencyInjection/ConfigurationTest.php

I am targetting this branch, because this is BC.
```markdown
- Added the possibility to configure the timeout to clear the Symfony cache.
```
The timeout to clear the Symfony cache was hard-coded (2 seconds), I add some configuration to be able to tweak it as you want.

Configured timeout to clear Symfony cache

---

Adapter/VarnishCache.php
Tests/Adapter/VarnishCacheTest.php

I am targetting this branch, because this is a bug fix.
```markdown
- Fixed variable conflict when multiple Varnish servers are configured
```
When multiple Varnish servers are configured, the `$command` argument is lost in the `runCommand` method.

Fixed variable conflict when multiple Varnish servers are configured

---

Adapter/SymfonyCache.php
Tests/Adapter/SymfonyCacheTest.php
composer.json

I am targetting this branch, because bumping minor versions of dependencies is considered major.
Closes #120 
```markdown
- PHP 5.3 through 5.5 support was removed
- Symfony 2.2 through 2.7 support was removed
```
This prepares the next major release.

Drop old versions

---

Adapter/MemcachedCache.php
Adapter/MongoCache.php
Adapter/NoopCache.php
Adapter/PRedisCache.php
Cache/CacheInterface.php
Cache/CacheManager.php
Cache/CacheManagerInterface.php
Invalidation/DoctrineORMListener.php
Invalidation/DoctrinePHPCRODMListener.php
Invalidation/InvalidationInterface.php
Invalidation/ModelCollectionIdentifiers.php
Invalidation/Recorder.php
Invalidation/SimpleCacheInvalidation.php
UPGRADE-2.x.md

I am targetting this branch, because this is BC and introduced already introduced deprecations.
As per definition, i mark this PR as `minor`!
```markdown
- `Sonata\CacheBundle\Invalidation\SimpleCacheInvalidation`, use `Sonata\Cache\Invalidation\SimpleCacheInvalidation` instead.
- `Sonata\CacheBundle\Invalidation\Recorder`, use `Sonata\Cache\Invalidation\Recorder` instead.
- `Sonata\CacheBundle\Invalidation\ModelCollectionIdentifiers`, use `Sonata\Cache\Invalidation\ModelCollectionIdentifiers` instead.
- `Sonata\CacheBundle\Invalidation\InvalidationInterface`, use `Sonata\Cache\Invalidation\InvalidationInterface` instead.
- `Sonata\CacheBundle\Invalidation\DoctrinePHPCRODMListener`, use `Sonata\Cache\Invalidation\DoctrinePHPCRODMListener` instead.
- …
```

Handle deprecations with trigger_error()

---

DependencyInjection/Configuration.php

I am targeting this branch, because it does not break anything, and adds functionality for those needing secure Redis instances through Predis.
```markdown
- Added password configuration option under Predis cache configuration.
```
Some users might be using a password protected Redis instance. This modification allows for the use of a password that is sent directly to Predis from the Sonata Cache configuration.  It is an optional field.

Added password option to Predis in configuration.

---

Adapter/ApcCache.php
phpunit.xml.dist

I am targeting this branch, because this is pedantic.
I think coverage is not calculated correctly, lets see

Remove exceptions from phpunit whitelist

---

Adapter/ApcCache.php
Adapter/SymfonyCache.php
Resources/doc/reference/installation.rst
Tests/Adapter/ApcCacheTest.php
composer.json

I am targeting this branch, because this is BC.
```markdown
- Support for PHP <7.1
```
This PR drops support for PHP <7.1, as listed in https://github.com/sonata-project/dev-kit/issues/216

Remove support for PHP <7.1

---

Tests/Adapter/ApcCacheTest.php
Tests/Adapter/SsiCacheTest.php
Tests/Adapter/SymfonyCacheTest.php
Tests/Adapter/VarnishCacheTest.php
Tests/DependencyInjection/ConfigurationTest.php

I am targeting this branch, because this is BC.
Removed compatibility with PHPUnit 4. Fixes: https://github.com/sebastianbergmann/phpunit/issues/2809

Drop PHPUnit 4 support

---

Adapter/SsiCache.php
Adapter/SymfonyCache.php
Adapter/VarnishCache.php
Tests/Adapter/SymfonyCacheTest.php
UPGRADE-3.0.md
composer.json

I am targeting this branch, because this might be considered BC.
```markdown
- support for sonata/cache 2
- support for sonata/cache 1
```
Support for sonata/cache 1 is dropped because keeping it would imply
duplicating all the code in the cache adapters just to achieve
compatibility with the CacheAdapterInterface in both of its versions.

Cache2 support

---

Adapter/ApcCache.php
Adapter/SsiCache.php
Adapter/SymfonyCache.php
Adapter/VarnishCache.php
Command/BaseCacheCommand.php
Command/CacheFlushAllCommand.php
Command/CacheFlushCommand.php
DependencyInjection/Compiler/CacheCompilerPass.php
DependencyInjection/Configuration.php
DependencyInjection/SonataCacheExtension.php
Invalidation/DoctrineORMListenerContainerAware.php
Invalidation/DoctrinePHPCRODMListenerContainerAware.php
SonataCacheBundle.php
Tests/Adapter/ApcCacheTest.php
Tests/Adapter/SsiCacheTest.php
Tests/Adapter/SymfonyCacheTest.php
Tests/Adapter/VarnishCacheTest.php
Tests/DependencyInjection/ConfigurationTest.php
Twig/TwigTemplate13.php
Twig/TwigTemplate14.php

```markdown
- type hinting on most function signatures
```
I avoided touching 2 classes that are most likely be tested because they extend `\TwigTemplate`, and twig isn't even required at the moment, see #158

Add type hinting

---

composer.json
src/DependencyInjection/SonataCacheExtension.php
tests/DependencyInjection/SonataCacheExtensionTest.php

I'm targeting `2.x` branch because it does not introduce any backward incompatible change.
Closes #166 
```markdown
- DoctrineBundle and DoctrinePHPCRBundle can be loaded before or after SonataCacheBundle.
```
This will improve DX when bundle is used with Symfony Flex. I wanted to add tests but this bundle does not depend on `symfony/framework-bundle`. Can I add it to dependencies and write some tests?

remove use of other bundles parameters in dependency injection extension

---

UPGRADE-2.x.md
src/Twig/TwigTemplate13.php
src/Twig/TwigTemplate14.php

I am targeting this branch, because it's targeting twig v2, which has no support for getAttribute anymore.
Related to #158
```markdown
- Deprecation warning when using `\Twig_Template::getAttribute` function.
```
As discussed in #158, twig dropped support for \Twig_Template::getAttribute, so we can't override it anymore. There is no solution for this problem yet, so I've added a deprecation warning and a request to create an issue when encountering issues related to cache invalidation.
I'm not very good at creating good explainatory messages, so please any feedback is welcomed.

Show deprecation when using unsupported twig getAttribute function

---

src/Adapter/ApcCache.php
tests/autoload.php.dist

This is a missing change from refactor structure, pretty critical because it makes test unable to execute but still gives a green build

fix autoload routes for testing

---

UPGRADE-2.x.md
composer.json
phpunit.xml.dist
src/Adapter/SsiCache.php
src/Adapter/VarnishCache.php
tests/Adapter/SsiCacheTest.php
tests/Adapter/SymfonyCacheTest.php
tests/Adapter/VarnishCacheTest.php

I am targeting this branch, because this is BC.
```markdown
- omitting the `$argumentsResolver` argument when instanciating `SsiCache` or `VarnishCache`
- deprecation about using a `ControllerResolverInterface` to resolve arguments
```
This should make the bundle compatible with sf 3.4 and sf 4.0 according to the test suite.

Forward compatibility

---

composer.json

```markdown
-  Symfony 4.0 for `symfony/config`
```
I realized that Symfony 4.0 isn't available for config component.

make symfony/config allowed for symfony 4.0

---

composer.json

I am targeting this branch, because it fixes things that are only on master, strangely.
None since this is master and stable does not have these issues

Clean composer

---

src/DependencyInjection/SonataCacheExtension.php
src/Resources/config/command.xml

I am targeting this branch, because this is a BC fix.
```markdown
- Commands not working on symfony4
```
On symfony4 commands are not working as they are not registered as a services, this fixes it.

Commands as services

---

src/SonataCacheBundle.php

I am targeting this branch, because this is a patch.
See #206
```markdown
- Usage of twig service in SonataCacheBundle is optional now
```
To find Twig base template class, Sonata\CacheBundle\SonataCacheBundle::boot method gets twig service from container and does not check if it exists.

Optional usage of twig service

---

src/SonataCacheBundle.php

I am targeting this branch, because this is a BC break.
```markdown
- removed calling deprecated twig classes in bundle boot
```
This should have been part of https://github.com/sonata-project/SonataCacheBundle/pull/204 but I did not see it, so let's remove it.

Remove deprecated twig

---

src/Resources/config/cache.xml

I am targeting this branch, because this is a patch.
```markdown
- Fixed sonata.cache.invalidation.simple service definition typo
```
`Sonata\CacheBundle\Invalidation\SimpleCacheInvalidation` class is deprecated in 2.x branch and was moved to `sonata-project/cache` package to `Sonata\Cache\Invalidation\SimpleCacheInvalidation` in master

Fix sonata.cache.invalidation.simple service definition

---

composer.json
src/Cache/TwigTemplateRecorderInjector.php
src/Resources/config/cache.xml
src/SonataCacheBundle.php

I am targeting this branch, because this backwards-compatible optimization.
```markdown
- Twig is no longer initialized on container boot
```
I was originally planning using [service configurator](http://symfony.com/doc/current/service_container/configurators.html) but turns out there can be only one and TwigBundle adds one by default...
~So I resorted to this ugly hack. This should theoretically work and I manually checked the dumped container - but it would be nice if someone tested this with a live app.~
~The only thing I'm not sure about is the order: before we would get a fully-ready twig instance, now it's place in middle of initialization process...~
Found a better approach - but it would be still nice if someone tested this with a live app

Fix twig init on boot

---

src/Adapter/SsiCache.php
src/Adapter/SymfonyCache.php
src/Adapter/VarnishCache.php
tests/Adapter/SsiCacheTest.php
tests/Adapter/VarnishCacheTest.php

So CacheBundle is 2.x currenly, not 3.x.

Fix wrong version of depreaction message

---

src/Resources/config/orm.xml

I am targeting this branch, because this is BC.
closes #217 
```markdown
- definition pointing to a non existent class
```
Not a BC break because it doesn't work now as expected.

Make service definition point to the correct class

---

src/Resources/config/phpcr_odm.xml

```markdown
- Wrong namespace for `sonata.cache.phpcr_odm.event_subscriber.default` config
- `sonata.cache.phpcr_odm.event_subscriber.default`is now `public`
```

use the class from cache component and make service public

---

src/Adapter/SymfonyCache.php
src/Command/CacheFlushAllCommand.php
src/Command/CacheFlushCommand.php
src/Resources/config/cache.xml
tests/Adapter/SymfonyCacheTest.php

I am targeting this branch, because it does not introduce a BC break.
Clearing the symfony cache with command (and then by http request through socket) requires to set the event dispatcher stateless to avoid further events to be called/executed without cache, which currently raises an error (even if the cache is well cleared).
Executing flush command leads to:
```
~/html/test $ bin/console sonata:cache:flush-all --env=prod
[2019-04-30 19:38:32] Executing command bin/console 'sonata:cache:flush-all' --env=prod
clearing cache information
> sonata.page.cache.js_sync : starting .... OK
> sonata.page.cache.js_async : starting .... OK
> sonata.cache.noop : starting .... OK
> sonata.cache.predis : starting .... OK
> sonata.cache.symfony : starting .... FAILED!
done!
Warning: …
```

fix(symfony cache): fix error raised by listeners on symfony cache clear

---

src/Resources/config/cache.xml

The ESI and SSI cache requires an extra parameter for the `argument_resolver` service which is not currently defined in the service definition
I am targeting this branch, because it is a bug fix.
```markdown
- missing argument for SSI and ESI cache
```

Add argument_resolver service to SSI and ESI cache

---

.travis.yml
composer.json
src/Command/CacheFlushAllCommand.php
src/Command/CacheFlushCommand.php
tests/Adapter/SymfonyCacheTest.php

Allow Symfony 5 components in composer.json
I am targeting this branch because it is backwards compatible.
```markdown
- Added symfony 5 components in composer.json
- Removed support for symfony 3
```

Allow Symfony 5 in composer.json

---

src/Command/CacheFlushAllCommand.php
src/Command/CacheFlushCommand.php

When installing SonataCacheBundle using PHP version 7.4.1 a compile error is thrown because the `execute` method in the CacheFlushCommand is a void method but returns a 0 if it is run successfully. Symfony requires a proper exit code to be set so an integer should always be returned when calling these methods.
I am targeting this branch, because it is a patch.
- Removed `void` return type declarations from the command execute methods
- Added `int` return type declarations to the command execute methods

Change void return declarations commands to be integer returns
